service: serverless-docker-example

provider:
  name: aws
  ecr:
    images:
      python:
        path: ./
        file: Dockerfile

functions:
  hello:
    timeout: 60
    image:
      name: python
    events:
      - httpApi:
          path: /hello
          method: post